// Regenerate src/types.ts from the live database schema.
// Requires SUPABASE_DB_URL in the repo-root .env (dashboard → Connect → Direct).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { config } from "dotenv";

const pkgDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
config({ path: path.resolve(pkgDir, "../../.env") });

const dbUrl = process.env.SUPABASE_DB_URL;
if (!dbUrl) {
  console.error(
    "SUPABASE_DB_URL is not set. Add the direct Postgres connection string to the repo-root .env, then re-run `npm run gen:types`.",
  );
  process.exit(1);
}

const out = execFileSync(
  process.platform === "win32" ? "npx.cmd" : "npx",
  ["--yes", "supabase", "gen", "types", "typescript", "--db-url", dbUrl, "--schema", "public"],
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, shell: process.platform === "win32" },
);

const header = `// Generated by \`npm run gen:types\` — do not edit by hand.\n\n`;
writeFileSync(path.join(pkgDir, "src", "types.ts"), header + out);
console.log("Wrote packages/db/src/types.ts from live schema.");
